# Generated by Django 5.2 on 2025-05-06 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Content of the notification')),
                ('notification_type', models.CharField(blank=True, help_text='Category or type of notification (e.g., "SwapRequest", "LeaveApproval")', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('is_read', models.BooleanField(default=False, help_text='Marks whether the recipient has read the notification')),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
