services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: django
    # mount your entire project into /app
    volumes:
      - .:/app
    # make /app/src your working directory
    working_dir: /app/src
    # wait for MySQL, then run migrations + server
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  mysql_data:
