version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: django
    command: >
      sh -c "while ! nc -z db 3306; do sleep 1; done &&
            python src/manage.py migrate &&
            python src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  mysql_data:
