# Generated by Django 5.2 on 2025-05-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='assigned_course_offerings',
            field=models.ManyToManyField(blank=True, help_text='Course offerings this instructor is teaching', related_name='assigned_instructors', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this student is enrolled in.', related_name='enrolled_students', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='assigned_course_offerings',
            field=models.ManyToManyField(blank=True, related_name='assigned_tas', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='enrolled_course_offerings',
            field=models.ManyToManyField(blank=True, related_name='enrolled_tas', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='taprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ta_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
