# Generated by Django 5.2.1 on 2025-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='is_ta_coordinator',
            field=models.BooleanField(default=False, help_text='Whether this instructor is responsible for managing TA assignments'),
        ),
    ]
