# Generated by Django 5.2.1 on 2025-05-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='classroom',
        ),
        migrations.AddField(
            model_name='exam',
            name='classroom',
            field=models.ManyToManyField(blank=True, help_text='Room where the exam will be held', related_name='exams', to='courses.classroom'),
        ),
    ]
