# Generated by Django 5.2.1 on 2025-05-10 14:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        ('duties', '0002_leaverequest_swaprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_object_id', models.PositiveIntegerField(help_text='PK of the duty being logged')),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hours_spent', models.FloatField(help_text='Hours worked')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the log was approved/rejected', null=True)),
                ('duty_content_type', models.ForeignKey(help_text='Content type for the duty being logged', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff user who approved/rejected this log', limit_choices_to={'role__in': ['INSTRUCTOR', 'SECRETARY', 'DEPT_CHAIR', 'DEAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_duty_logs', to=settings.AUTH_USER_MODEL)),
                ('ta_profile', models.ForeignKey(help_text='TA who logged this duty', on_delete=django.db.models.deletion.CASCADE, related_name='duty_logs', to='accounts.taprofile')),
            ],
            options={
                'ordering': ['-date_logged'],
            },
        ),
        migrations.CreateModel(
            name='TACourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taprofile')),
            ],
        ),
    ]
