# Generated by Django 5.2.1 on 2025-05-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_exam_classroom_exam_classroom'),
        ('duties', '0002_leaverequest_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringduty',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Classroom where this TA will proctor the exam', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctoring_duties', to='courses.classroom'),
        ),
    ]
