# Generated by Django 5.2.1 on 2025-05-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_exam_classroom_exam_classroom'),
        ('duties', '0003_proctoringduty_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringduty',
            name='course',
            field=models.ForeignKey(default=1, help_text='Course for this duty', on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_duties', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gradingduty',
            name='offering',
            field=models.ForeignKey(blank=True, default=None, help_text='Course offering this duty belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sduties', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='labduty',
            name='offering',
            field=models.ForeignKey(blank=True, default=None, help_text='Course offering this duty belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sduties', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='officehourduty',
            name='offering',
            field=models.ForeignKey(blank=True, default=None, help_text='Course offering this duty belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sduties', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='proctoringduty',
            name='offering',
            field=models.ForeignKey(blank=True, default=None, help_text='Course offering this duty belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sduties', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='recitationduty',
            name='offering',
            field=models.ForeignKey(blank=True, default=None, help_text='Course offering this duty belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)sduties', to='courses.courseoffering'),
        ),
    ]
