# Generated by Django 5.2.1 on 2025-05-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0003_dutylog_tacourseassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swaprequest',
            name='duty_content_type',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='from_ta',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='to_ta',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='SwapRequest',
        ),
    ]
