# Generated by Django 5.0.4 on 2025-05-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0004_proctoringduty_course_alter_gradingduty_offering_and_more'),
        ('duties', '0004_remove_swaprequest_duty_content_type_and_more'),
    ]

    operations = [
    ]
