# Generated by Django 5.2.1 on 2025-05-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_instructorprofile_is_ta_coordinator'),
        ('duties', '0004_proctoringduty_course_alter_gradingduty_offering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingduty',
            name='assigned_ta_list',
            field=models.ManyToManyField(blank=True, help_text='TA assigned to this duty', related_name='%(class)sdutiees', to='accounts.taprofile'),
        ),
        migrations.AddField(
            model_name='labduty',
            name='assigned_ta_list',
            field=models.ManyToManyField(blank=True, help_text='TA assigned to this duty', related_name='%(class)sdutiees', to='accounts.taprofile'),
        ),
        migrations.AddField(
            model_name='officehourduty',
            name='assigned_ta_list',
            field=models.ManyToManyField(blank=True, help_text='TA assigned to this duty', related_name='%(class)sdutiees', to='accounts.taprofile'),
        ),
        migrations.AddField(
            model_name='proctoringduty',
            name='assigned_ta_list',
            field=models.ManyToManyField(blank=True, help_text='TA assigned to this duty', related_name='%(class)sdutiees', to='accounts.taprofile'),
        ),
        migrations.AddField(
            model_name='recitationduty',
            name='assigned_ta_list',
            field=models.ManyToManyField(blank=True, help_text='TA assigned to this duty', related_name='%(class)sdutiees', to='accounts.taprofile'),
        ),
    ]
