# Generated by Django 5.0.4 on 2025-05-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0005_gradingduty_assigned_ta_list_and_more'),
        ('duties', '0005_merge_20250510_1902'),
    ]

    operations = [
    ]
