# Generated by Django 5.2.1 on 2025-05-10 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='First day of leave')),
                ('end_date', models.DateField(help_text='Last day of leave')),
                ('reason', models.TextField(help_text='Reason for leave request')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', help_text='Approval status of the request', max_length=1)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when request was submitted')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was processed', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff user who processed the request', limit_choices_to={'role__in': ['INSTRUCTOR', 'SECRETARY', 'DEPT_CHAIR', 'DEAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('ta_profile', models.ForeignKey(help_text='TA requesting leave', on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.taprofile')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_object_id', models.PositiveIntegerField(help_text='Primary key for the duty being swapped')),
                ('reason', models.TextField(help_text='Reason for swap')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='Timestamp when the request was processed', null=True)),
                ('duty_content_type', models.ForeignKey(help_text='Content type for the duty being swapped', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('from_ta', models.ForeignKey(help_text='TA initiating the swap request', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='accounts.taprofile')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Staff user who processed the request', limit_choices_to={'role__in': ['INSTRUCTOR', 'SECRETARY', 'DEPT_CHAIR', 'DEAN', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_swap_requests', to=settings.AUTH_USER_MODEL)),
                ('to_ta', models.ForeignKey(help_text='TA requested to take over the duty', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='accounts.taprofile')),
            ],
            options={
                'verbose_name': 'Swap Request',
                'verbose_name_plural': 'Swap Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
